### ISSUE TITLE
[Odoo 10][voip_sip_webrtc] Permission denied error.

### ISSUE THREAD

**Issue by anthoviso** [SythilTech/Odoo10#11]
Hello,

I am admin and i call a user :
1- Windows -> firefox : Ok.
2- Windows -> Chrome : Uncaught TypeError: Illegal invocation
3- Windows -> IE 10 : Ask Caller permission

I am a user and admin is calling me :
Windows and Linux (chrome/firefox) : Nothing happen. I receive the call but i can't accept because there are no messages for permissions.
--> linux errors : Fail to access to media.

When i call someone (firefox) and i choose "End call" , i can't close the call's window.
thanks for your work.

**Comment by SythilTech** [comment]
Hello,

I have released a new version of the module (v1.2.5) which should add support for Chrome.
At the moment I do not intent to support IE, this may change at a later date when webrtc becomes more uniform across the major browsers.

**Comment by anthoviso** [comment]
thanks a lot

**Comment by ko90thu** [comment]
Hi 
I tested for this case as per anthoviso issues description:
I am a user and admin is calling me :
Windows and Linux (chrome/firefox) : Nothing happen. I receive the call but i can't accept because there are no messages for permissions.
--> linux errors : Fail to access to media.

"Fail to access to media" at ubuntu chrome show that is used by user.

**Comment by ko90thu** [comment]
Hi 
Sorry for my issues comment.
I run google chrome following and it get it because of https problem.
google-chrome --unsafely-treat-insecure-origin-as-sure="http://192.168.43.214:8069" --user-data-dir=/test/only/profile/dir

**Comment by SythilBlade** [comment]
Yea Chrome requires requires https, that command can bypass that requirement which is handy for testing.

A lot of sensitive data does get exchanged so I can understand why Chrome is so strict on forcing  an encrypted connection.
