### ISSUE TITLE
[10.0][html_form_builder] Checkbox Group error

### ISSUE THREAD

**Issue by jbofill** [SythilTech/Odoo10#15]
Hello,

when I submit a form that has a Checkbox Group I get the following error:

`  File "/home/jordi/work/manresa/odoo/community.addons10/html_form_builder/controllers/main.py", line 607, in my_secure_insert
    return self.process_form(kwargs)
  File "/home/jordi/work/manresa/odoo/community.addons10/html_form_builder/controllers/main.py", line 549, in process_form
    field_valid = action(fi, values[fi.html_name], values)
  File "/home/jordi/work/manresa/odoo/community.addons10/html_form_builder/controllers/main.py", line 662, in _process_html_checkbox_group
    create_list = []
TypeError: 'int' object is not iterable
`

**Comment by SythilTech** [comment]
Hello,

Sorry I am not able to reproduce this issue, can you please update to the latest version (1.0.13) and restart your Odoo instance.
If you are still encountering the error can you please provide additional details

Regards
Steven

**Comment by jbofill** [comment]
I am using latest version.
The error is raised when you select only one item of the checkbox list, if you select more than one item it works as expected.

**Comment by SythilTech** [comment]
Hello,

Thank you providing additional details on how to reproduce the issue.

I have released a new version (1.0.14) which should fix this issue, you will need to restart your Odoo instance for code changes to take effect.

Regards
Steven

**Comment by jbofill** [comment]
Sorry for not being more specific before. Yes, it works now. Thank-you! 

I have 2 more issues (if you prefer I can create new issue entries):

1. Required fields are ignored when checked in popup windows (at least for Textbox and Checkbox)
2. I'm getting a unicode error
`File "/home/jordi/work/manresa/odoo/community.addons10/html_form_builder/controllers/main.py", line 315, in _generate_html_checkbox_group
    html_output += "    <label><input type=\"checkbox\" value=\"" + str(my_record.id) + "\" name=\"" + field.html_name.encode("utf-8") + "\"/>" + my_record.name.encode("utf-8") + "</label>\n"
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 88: ordinal not in range(128)`
that can be fixed removing encode("utf-8") from my_record.name:
`html_output += "    <label><input type=\"checkbox\" value=\"" + str(my_record.id) + "\" name=\"" + field.html_name.encode("utf-8") + "\"/>" + my_record.name + "</label>\n"`

**Comment by jbofill** [comment]
Also, when I click "Generate External Website Embed Code" in create form, I get the following error:

`File "/home/jordi/work/manresa/odoo/community.addons10/html_form_builder/models/html_form.py", line 62, in generate_form
    raise NotImplementedError('Method %r is not implemented on %r object.' % (method, self))
NotImplementedError: Method u'_generate_html_checkbox_group' is not implemented on html.form(1,) object.`

**Comment by SythilTech** [comment]
Hello,

I have released a new version (1.0.15) which should fix the unicode error and allow you to generate external website forms with checkbox groups in them.

Can you please describe what module you are using for popups?

Regards
Steven

**Comment by jbofill** [comment]
Here is a screenshot. 

![required](https://user-images.githubusercontent.com/1204089/27986867-87e22bfe-6405-11e7-808b-0358824a87e6.png)

**Comment by SythilTech** [comment]
Hello,

Thank you for bringing this issue to my attention.

The new version should now correctly tag fields as required when using the customise field popup.

Regards
Steven

**Comment by jbofill** [comment]
Works perfectly, thank-you!
