### ISSUE TITLE
Click End Call Problem in voip_sip_webrtc

### ISSUE THREAD

**Issue by ko90thu** [SythilTech/Odoo10#18]
When i click end call button before picking up by others, there has problem.
"Uncaught TypeError: remoteStream.getTracks is not a function"

**Comment by SythilTech** [comment]
Thank you for bring this to my attention.

I have released a new version (1.3.1) which should allow for calls to be ended before they are picked up using the end call button.

Regards
Steven

**Comment by ko90thu** [comment]
Thanks you very much Steven.
It works well on your new version.
