### ISSUE TITLE
Extend HTML Form Builder to create event

### ISSUE THREAD

**Issue by redford-jones** [SythilTech/Odoo10#7]
Hi - hoping you can point me in the right direction?
I'm looking to extend the HTML form builder add on to include the 'Event' type model. We have an internal portal that we are wanting to looking to deploy where we allow non-management users access to create events using the Website app and have no access to the backend event creation forms. Similar  to how you use HTML Form builder to create a lead.

Is this possible? Could you point me in the direction of where I would add the event model as an option?

Many Thanks

**Comment by SythilTech** [comment]
Hi,Yes this is possible, you can go to settings->html forms and choose whatever model you want.RegardsStevenOn 15 May 2017 10:39 PM, redford-jones <notifications@github.com> wrote:Hi - hoping you can point me in the right direction?
I'm looking to extend the HTML form builder add on to include the 'Event' type model. We have an internal portal that we are wanting to looking to deploy where we allow non-management users access to create events using the Website app and have no access to the backend event creation forms. Similar  to how you use HTML Form builder to create a lead.
Is this possible? Could you point me in the direction of where I would add the event model as an option?
Many Thanks

**Comment by redford-jones** [comment]
Perfect. Thanks for the help.
